main: eu.software4you.cloudnetlobby.Lobby
name: CloudNet-Lobby
version: 1.0
depend: [McUtils, CloudNetAPI]
softdepend: [McUtils, CloudNetAPI, PlaceholderAPI]
author: 'Software4You.eu (fluse1367, TheActualOne, BlockStudiosHD, DashBlizz, DashBlitz)'
website: https://software4You.eu